# Generated by Django 4.0 on 2022-04-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_addmember_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmember',
            name='pic',
            field=models.FileField(default='avatar.jpg', upload_to='profile'),
        ),
    ]
