# Generated by Django 4.2.4 on 2023-10-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_addmember_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
